// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/users" | "/dashboard" | "/dashboard/doctor" | "/dashboard/mr" | "/doctors" | "/login" | "/privacy" | "/signup" | "/status-board" | "/terms" | "/update/[key]" | "/welcome"
type AppRouteHandlerRoutes = "/api/admin/users" | "/api/auth/[...nextauth]" | "/api/call-requests" | "/api/call-requests/[id]" | "/api/doctors" | "/api/doctors/[id]" | "/api/doctors/[id]/day-plan" | "/api/doctors/[id]/status" | "/api/doctors/[id]/status-key" | "/api/doctors/[id]/timetable" | "/api/doctors/[id]/verify" | "/api/doctors/claim" | "/api/doctors/me" | "/api/mrs" | "/api/my-doctors" | "/api/patches" | "/api/plan" | "/api/signup" | "/api/status-link/[key]" | "/api/users/[id]" | "/api/visits"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/users": {}
  "/api/admin/users": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/call-requests": {}
  "/api/call-requests/[id]": { "id": string; }
  "/api/doctors": {}
  "/api/doctors/[id]": { "id": string; }
  "/api/doctors/[id]/day-plan": { "id": string; }
  "/api/doctors/[id]/status": { "id": string; }
  "/api/doctors/[id]/status-key": { "id": string; }
  "/api/doctors/[id]/timetable": { "id": string; }
  "/api/doctors/[id]/verify": { "id": string; }
  "/api/doctors/claim": {}
  "/api/doctors/me": {}
  "/api/mrs": {}
  "/api/my-doctors": {}
  "/api/patches": {}
  "/api/plan": {}
  "/api/signup": {}
  "/api/status-link/[key]": { "key": string; }
  "/api/users/[id]": { "id": string; }
  "/api/visits": {}
  "/dashboard": {}
  "/dashboard/doctor": {}
  "/dashboard/mr": {}
  "/doctors": {}
  "/login": {}
  "/privacy": {}
  "/signup": {}
  "/status-board": {}
  "/terms": {}
  "/update/[key]": { "key": string; }
  "/welcome": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
