// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/doctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/doctor">> = Specific
  const handler = {} as typeof import("../../app/dashboard/doctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/mr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mr">> = Specific
  const handler = {} as typeof import("../../app/dashboard/mr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctors">> = Specific
  const handler = {} as typeof import("../../app/doctors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/status-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status-board">> = Specific
  const handler = {} as typeof import("../../app/status-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/update/[key]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/update/[key]">> = Specific
  const handler = {} as typeof import("../../app/update/[key]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../app/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/call-requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/call-requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/call-requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/call-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/call-requests">> = Specific
  const handler = {} as typeof import("../../app/api/call-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/day-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]/day-plan">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/day-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/status-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]/status-key">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/status-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/timetable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]/timetable">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/timetable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/[id]/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/[id]/verify">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/[id]/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/claim">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors/me">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctors">> = Specific
  const handler = {} as typeof import("../../app/api/doctors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mrs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mrs">> = Specific
  const handler = {} as typeof import("../../app/api/mrs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/my-doctors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/my-doctors">> = Specific
  const handler = {} as typeof import("../../app/api/my-doctors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/patches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/patches">> = Specific
  const handler = {} as typeof import("../../app/api/patches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan">> = Specific
  const handler = {} as typeof import("../../app/api/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signup">> = Specific
  const handler = {} as typeof import("../../app/api/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/status-link/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status-link/[key]">> = Specific
  const handler = {} as typeof import("../../app/api/status-link/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visits">> = Specific
  const handler = {} as typeof import("../../app/api/visits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
